before_install:
  - bash scripts/install.sh
script:
  - bash scripts/build.sh
  - bash scripts/test.sh
after_success:
  - bash scripts/deploy.sh
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
